spring:
  application:
    name: audiovisualiser-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-fragrant-scene-a7clvhg6-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_AV_API_KEY:}
  org-id: iLucaH
  project-id: AudioVisualiser

rsa:
  private-key: ${AV_PRIVATE_KEY}
  public-key: ${AV_PUBLIC_KEY}

server:
  port: 8080
