spring:
  application:
    name: audiovisualiser-service
  h2:
    console:
      enabled: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ticket
#    username: root
#    password: cisco
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto:update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_AV_API_KEY:}
  org-id: iLucaH
  project-id: AudioVisualiser

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  port: 8080